<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Kendaraan</name>
   <tag></tag>
   <elementGuidId>26e03d94-f9a1-4c7e-b87d-414aacbf5e71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[3]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>f119bb5f-b008-4cdf-a65d-78dee5bbd4f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bi bi-search me-3 fs-4</value>
      <webElementGuid>c52c7078-fe51-4fef-871a-1890edf4bf32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;pt-5 mt-5&quot;]/section[@class=&quot;container&quot;]/nav[@class=&quot;nav row gap-4 px-2 px-lg-0&quot;]/a[@class=&quot;btn btn-alt-primary col rounded-4 py-2 px-4 d-inline-flex align-items-center false&quot;]/i[@class=&quot;bi bi-search me-3 fs-4&quot;]</value>
      <webElementGuid>43fa8880-2113-43ba-983b-45431a4a44d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/i</value>
      <webElementGuid>75457ead-1c48-4cf8-8851-1ab7db93a7b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
